title: "The Future of Mathematical Finance"
author: "Department of Statistical Sciences, University of Toronto"
email: "communications.statistics@utoronto.ca"

description: >
  The Future of Mathematical Finance: Celebrating U of T at 200 brings
  together researchers and leaders in mathematical finance at the
  University of Toronto.

# Site URL
baseurl: "/"
url: "https://uoftstatsci.github.io"

# Social metadata
social:
  name: "Department of Statistical Sciences, University of Toronto"
  links:
    - https://www.instagram.com/uoftstatsci/
    - https://www.linkedin.com/school/uoftstatsci/
    - https://www.statistics.utoronto.ca/

# Build settings
markdown: kramdown
highlighter: rouge

exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.png

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
